### ISSUE TITLE
示例有报错

### ISSUE THREAD

**Issue by dengshenkk** [Simon-Bin/flant#3]
### 在这个示例中 [示例链接](https://flant.netlify.app/#/) 选择cell, 然后在页面导航部分, 分别来回点击路由跳转和url跳转, 跳转后左上角点击返回, 然后继续点, 点3轮左右就会报错, 然后点不动了

**Comment by Binbiubiubiu** [comment]
升级到最新版本flutter版本,路由bug就没有了
